--1 LAST_NAME 이 Zlotkey 와 동일한 부서에 근무하는 모든 사원들의 사번 및 고용날짜를 조회한다.
--(결과값에서 Zlotkey 는 제외한다.)
SELECT EMPLOYEE_ID,HIRE_DATE
FROM EMPLOYEES
WHERE LAST_NAME<>'Zlotkey' AND DEPARTMENT_ID=ANY(SELECT DEPARTMENT_ID
                                            FROM EMPLOYEES
                                            WHERE LAST_NAME='Zlotkey');
-- 사원이 존재하지 않는 국가를 조회하라
SELECT COUNTRY_NAME
FROM LOCATIONS LEFT JOIN DEPARTMENTS USING(LOCATION_ID) JOIN COUNTRIES USING(COUNTRY_ID) LEFT JOIN EMPLOYEES USING(DEPARTMENT_ID) 
GROUP BY COUNTRY_NAME HAVING COUNT(EMPLOYEE_ID)=0;


--3. --자신의 상사가 자신 보다 늦게 입사한 사원의 모든 정보를 조회하라.
SELECT *
FROM EMPLOYEES EA
WHERE HIRE_DATE <(SELECT HIRE_DATE
                FROM EMPLOYEES EB
                WHERE EB.EMPLOYEE_ID=EA.MANAGER_ID);
--4. --사원수가 가장 많은 도시의 이름을 조회하라.
SELECT CITY
FROM(SELECT CITY
FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID) JOIN LOCATIONS USING(LOCATION_ID)
GROUP BY CITY
ORDER BY COUNT(EMPLOYEE_ID) DESC)
WHERE ROWNUM<2;


--5. --담당 직무의 최대 연봉을 받고 있는 사원들의 모든 정보를 조회하라.
SELECT *
FROM EMPLOYEES EA
WHERE SALARY = (SELECT MAX(SALARY)
                FROM EMPLOYEES EB
                GROUP BY JOB_ID HAVING  EA.JOB_ID=EB.JOB_ID);
                
SELECT *
FROM EMPLOYEES EA
WHERE (EA.JOB_ID, EA.SALARY) IN 
    (SELECT JOB_ID, MAX(SALARY)
     FROM EMPLOYEES
     GROUP BY JOB_ID);
--6. 사원수가 가장 많은 도시에서 근무하는 모든 사원들의 연봉 총합을 조회하라.
SELECT CITY,SU
FROM(SELECT CITY,SUM(SALARY) SU
    FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID) JOIN LOCATIONS USING(LOCATION_ID)
    GROUP BY CITY
    ORDER BY COUNT(EMPLOYEE_ID) DESC)
WHERE ROWNUM<2;